### ISSUE TITLE
Problems with already existing contacts and groups

### ISSUE THREAD

**Issue by BlackForest2015** [mozillahispano/openwapp#132]
Hello,
because you ask for reporting any issues here I am. Note please that I am not a programmer.
I am using a ZTE OpenC, FFOS 1.3.
Since about 3 or 4 days I observe some strange effects.
I have no problems by creating new groups or new conversations.
But I have problems by using already existing groups. E.g. I can’t see online status of contacts, name of contact is not shown (only the phone number), I have a permanent loading symbol on the main page, by using existing groups there is a permanent loading contact message.
Anyway, thank you so much for your excellent job!

**Comment by Omega246** [comment]
Hello. First i have to say thx so much for your great work with this programm and your contribution.

Second, I have the exact same problem as BlackForest2015 has. At first i thought it was because of the new update of Firefox OS. But now, i know its something else.

I have a ZTE OpenC, too.
Software: Boot2Gecko 2.2.0.0-prerelease (aurora)
Update: 2015-06-01
Openwapp: 1.7.6-0-gbbe7016

**Comment by holztest08** [comment]
I have the same problem.

**Comment by bobcanthelpyou** [comment]
Same issue with v1.8.1

```
"Error while creating the group: 501" group-profile.js:107
Profile<._createGroup/<() group-profile.js:107
.init/pub.createGroup/_groupCreateRequests[id]() client.js:793
onGroupCreateFail() client.js:306
fireEvent/</<() coseme.js:7456
```

**Comment by Timmaks** [comment]
For me the problem is fixed . I not sure if whatsapp has chnaged things back or that it is my update to the latest 2.5 nightly version of firefoxos.

Can you check?

**Comment by Trynight** [comment]
With 2.0 i have the same problems... I will update to 2.5 today

**Comment by Trynight** [comment]
Ok the problem still exist with 2.5 .. I need to open/close the group many times to show contacts

**Comment by Timmaks** [comment]
Looks like whatsapp is messing around, it worked this morning but now it is broken again and i did not change anything

**Comment by bobcanthelpyou** [comment]
Maybe it is related to issues where loading of the groups take a lot of time like #66

**Comment by Timmaks** [comment]
And now it is ok again for me

**Comment by Timmaks** [comment]
I suspect this is fixed with the latest coseme changes,  please reopen if it is still a issue
